name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./orderManagement/pom.xml
          mvn clean package -f ./deliveryManagement/pom.xml
          mvn clean package -f ./inventoryManagement/pom.xml
          mvn clean package -f ./MyPage/pom.xml

      - name: Docker Build and push for OrderManagement
        uses: docker/build-push-action@v4
        with:
          context: ./orderManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ordermanagement:latest
            ghcr.io/${{ github.repository }}/ordermanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for DeliveryManagement
        uses: docker/build-push-action@v4
        with:
          context: ./deliveryManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deliverymanagement:latest
            ghcr.io/${{ github.repository }}/deliverymanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for InventoryManagement
        uses: docker/build-push-action@v4
        with:
          context: ./inventoryManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/inventorymanagement:latest
            ghcr.io/${{ github.repository }}/inventorymanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for MyPage
        uses: docker/build-push-action@v4
        with:
          context: ./MyPage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypage:latest
            ghcr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
            
