apiVersion: v1
kind: Service
metadata:
  name: inventoryManagement
  labels:
    app: inventoryManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventoryManagement