server:
  port: 8088

---

spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
      routes:
         - id: orderManagement
           uri: http://localhost:8082
           predicates:
            - Path=/orders/** /searchProducts/**/searchOrders/**
         - id: deliveryManagement
           uri: http://localhost:8083
           predicates:
            - Path=/productDeliveries/** 
         - id: inventoryManagement
           uri: http://localhost:8084
           predicates:
            - Path=/inventoryManagements/** 
         - id: MyPage
           uri: http://localhost:8085
           predicates:
            - Path=/messages/** /searchOrders/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://oauth:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: orderManagement
          uri: http://orderManagement:8080
          predicates:
            - Path=/orders/** /searchProducts/**/searchOrders/**
        - id: deliveryManagement
          uri: http://deliveryManagement:8080
          predicates:
            - Path=/productDeliveries/** 
        - id: inventoryManagement
          uri: http://inventoryManagement:8080
          predicates:
            - Path=/inventoryManagements/** 
        - id: MyPage
          uri: http://MyPage:8080
          predicates:
            - Path=/messages/** /searchOrders/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080