server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: orderManagement
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: deliveryManagement
          uri: http://localhost:8083
          predicates:
            - Path=/productDeliveries/**, 
        - id: inventoryManagement
          uri: http://localhost:8084
          predicates:
            - Path=/inventoryManagements/**, 
        - id: MyPage
          uri: http://localhost:8085
          predicates:
            - Path=/messages/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: orderManagement
          uri: http://orderManagement:8080
          predicates:
            - Path=/orders/**, 
        - id: deliveryManagement
          uri: http://deliveryManagement:8080
          predicates:
            - Path=/productDeliveries/**, 
        - id: inventoryManagement
          uri: http://inventoryManagement:8080
          predicates:
            - Path=/inventoryManagements/**, 
        - id: MyPage
          uri: http://myPage:8080
          predicates:
            - Path=/messages/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
