---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderManagement
  labels:
    app: orderManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderManagement
  template:
    metadata:
      labels:
        app: orderManagement
    spec:
      containers:
        - name: orderManagement
          image: username/orderManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryManagement
  labels:
    app: deliveryManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryManagement
  template:
    metadata:
      labels:
        app: deliveryManagement
    spec:
      containers:
        - name: deliveryManagement
          image: username/deliveryManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryManagement
  labels:
    app: inventoryManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryManagement
  template:
    metadata:
      labels:
        app: inventoryManagement
    spec:
      containers:
        - name: inventoryManagement
          image: username/inventoryManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyPage
  template:
    metadata:
      labels:
        app: MyPage
    spec:
      containers:
        - name: MyPage
          image: username/MyPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: orderManagement
  labels:
    app: orderManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: orderManagement


---


apiVersion: v1
kind: Service
metadata:
  name: deliveryManagement
  labels:
    app: deliveryManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deliveryManagement


---


apiVersion: v1
kind: Service
metadata:
  name: inventoryManagement
  labels:
    app: inventoryManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventoryManagement


---


apiVersion: v1
kind: Service
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MyPage

